# Generated by Django 4.2.5 on 2023-11-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
